services:
  postgres-gorm:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres-gorm
      POSTGRES_PORT: 5432
      POSTGRES_SSLMODE: disable
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: my-health-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    command: ['go', 'run', 'main.go']
    depends_on:
      - postgres-gorm
    environment:
      SECRET: vNrSf+JwRpc/11gHFu6EdfO2pOSXEfLNlapBkShMBVQ=
      DB_HOST: postgres-gorm
      DB_USER: myuser
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
    volumes:
      - ./backend/:/my-health
    working_dir: /my-health

  frontend:
    container_name: my-health-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './frontend:/app'          # Mount the frontend source code
      - '/app/node_modules'         # Prevent node_modules from being overridden by the container
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn start"
    working_dir: /app  

volumes:
  db_data:
