version: '3.8'

services:
  postgres-gorm:
    image: postgres:13
    container_name: my-health-postgres-gorm-13-dev
    environment:
      POSTGRES_HOST: postgres-gorm
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-health-backend-dev
    environment:
      DB_HOST: postgres-gorm  # This is the key part
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "8080:8080"
    depends_on:
      - postgres-gorm
    links:
      - postgres-gorm

volumes:
  db_data:
